INSERT INTO public.blog_posts (title, slug, content, featured_image, status, published_at, created_at, updated_at) VALUES 
('Film Setlerinde Işık Kullanımının Önemi', 'film-setlerinde-isik-kullaniminin-onemi', '<h2>Film Setlerinde Işık Kullanımının Önemi</h2><p>Bir filmin atmosferini yaratan en önemli unsurların başında ışık gelir. Doğru aydınlatma ile sahnenin duygusunu tamamen değiştirebilirsiniz. Kariyerine yeni başlayan sinemacılar için ışık kurulumunun temellerine dair ipuçları bu yazımızda.</p>', 'https://villaqrmenu.b-cdn.net/nora/norasettenkareler/nora_yap%C4%B1m_settenkareler-1.webp', 'published', NOW(), NOW(), NOW()),

('Reklam Çekimlerinde Dikkat Edilmesi Gereken 5 Kural', 'reklam-cekimlerinde-dikkat-edilmesi-gereken-5-kural', '<h2>Reklam Çekimlerinde Dikkat Edilmesi Gereken 5 Kural</h2><p>Etkili bir reklam filmi çekmek için sadece iyi bir senaryo yetmez. Hedef kitle analizi, doğru sürede mesaj verme ve görsel hikaye anlatımı çok değerlidir. Markanızı bir adım öne taşıyacak çekim yöntemlerini inceliyoruz.</p>', 'https://villaqrmenu.b-cdn.net/nora/norasettenkareler/nora_yap%C4%B1m_settenkareler-2.webp', 'published', NOW(), NOW(), NOW()),

('Doğru Oyuncu Seçimi Projeyi Nasıl Değiştirir?', 'dogru-oyuncu-secimi-projeyi-nasil-degistirir', '<h2>Doğru Oyuncu Seçimi Projeyi Nasıl Değiştirir?</h2><p>Cast seçimi (oyuncu seçimi), bir yapımın başarısını ya da başarısızlığını belirleyen kilit faktörlerden biridir. Karakterin derinliğine uygun yüzleri ve yetenekleri seçmek sürecin zor ama en keyifli kısmıdır.</p>', 'https://villaqrmenu.b-cdn.net/nora/norasettenkareler/nora_yap%C4%B1m_settenkareler-3.webp', 'published', NOW(), NOW(), NOW()),

('Kamera Arkası: Bir Set Günü Nasıl Geçer?', 'kamera-arkasi-bir-set-gunu-nasil-gecer', '<h2>Kamera Arkası: Bir Set Günü Nasıl Geçer?</h2><p>Sabahın erken saatlerinde başlayan set hazırlıkları gün boyunca yoğun bir tempoda devam eder. Ekipler arası iletişim, planlama ve anlık kriz yönetimi bir set ortamının vazgeçilmezidir. Gelin bir set gününe yakından bakalım.</p>', 'https://villaqrmenu.b-cdn.net/nora/norasettenkareler/nora_yap%C4%B1m_settenkareler-4.webp', 'published', NOW(), NOW(), NOW()),

('Post Prodüksiyon: Sihrin Başladığı Yer', 'post-produksiyon-sihrin-basladigi-yer', '<h2>Post Prodüksiyon: Sihrin Başladığı Yer</h2><p>Çekimler bitmiş olabilir ama asıl büyü kurgu masasında başlar. Renk düzenlemesi (color correction), ses miksajı ve efektlerin birleşimi bir projeyi ham halinden alıp sinematik bir başyapıta dönüştürür.</p>', 'https://villaqrmenu.b-cdn.net/nora/norasettenkareler/nora_yap%C4%B1m_settenkareler-5.webp', 'published', NOW(), NOW(), NOW()),

('Yeni Nesil Kameralar ve Lens Teknolojileri', 'yeni-nesil-kameralar-ve-lens-teknolojileri', '<h2>Yeni Nesil Kameralar ve Lens Teknolojileri</h2><p>Son yıllarda hızla gelişen kamera sensörleri ve lens teknolojileri, yönetmenlerin vizyonunu daha geniş bir perspektifle ekrana yansıtmasına olanak tanıyor. Sektördeki en son ekipman trendlerini sizin için derledik.</p>', 'https://villaqrmenu.b-cdn.net/nora/norasettenkareler/nora_yap%C4%B1m_settenkareler-6.webp', 'published', NOW(), NOW(), NOW());
